package com.droidbytes.beans;

import java.util.Date;

public class EnergyUnit {
	private Date outputDate; // contains both date and time
	private long wattHourGenerated; // contains watthours generated by system
	private long wattHourConsumed; // contains watthours consumed
	
	
	public static void main(String[] args) {
		EnergyUnit su = new EnergyUnit();
		su.setOutputDate(new Date());
		su.setWattHourConsumed(10);
		su.setWattHourGenerated(14);
		System.out.println(su);
		
	}
	
	public Date getOutputDate() {
		return outputDate;
	}

	public void setOutputDate(Date outputDate) {
		this.outputDate = outputDate;
	}

	public long getWattHourGenerated() {
		return wattHourGenerated;
	}

	public void setWattHourGenerated(long wattHourGenerated) {
		this.wattHourGenerated = wattHourGenerated;
	}

	public long getWattHourConsumed() {
		return wattHourConsumed;
	}

	public void setWattHourConsumed(long wattHourConsumed) {
		this.wattHourConsumed = wattHourConsumed;
	}

	@Override
	public String toString() {
		//return String.format("%1$tY%1$tm%1$td,%1$tR,%2$d,-1,%3$d", outputDate,wattHourGenerated,wattHourConsumed); // format is date,generated,exported,peakpower,peaktime,condition,mintemp,maxtemp,comment,importpeak,importoffpeak,importshoulder,importhighshoulder,consumption
		return String.format("%1$tY%1$tm%1$td,%1$tR,%2$d,,%3$d", outputDate,wattHourGenerated,wattHourConsumed); // format is date,generated,exported,peakpower,peaktime,condition,mintemp,maxtemp,comment,importpeak,importoffpeak,importshoulder,importhighshoulder,consumption
	}

	public String getConsumptionDataString() {
		//20150923,16:01,0,,200;
		// here gen data will be 0 anyways
		return String.format("%1$tY%1$tm%1$td,%1$tR,0,-1,%2$d", outputDate,wattHourConsumed); // format is date,generated,exported,peakpower,peaktime,condition,mintemp,maxtemp,comment,importpeak,importoffpeak,importshoulder,importhighshoulder,consumption	
	}

	public String getGenerationDataString() {
		//20150923,16:01,1200,,-1
		// here we are using -1 to indicate to not update consumption data
		return String.format("%1$tY%1$tm%1$td,%1$tR,%2$d,,-1", outputDate,wattHourGenerated); // format is date,generated,exported,peakpower,peaktime,condition,mintemp,maxtemp,comment,importpeak,importoffpeak,importshoulder,importhighshoulder,consumption	
	}


	public EnergyUnit() {
		super();
	}
	
	public EnergyUnit(Date outputDate, long wattHourGenerated,
			long wattHourConsumed) {
		super();
		this.outputDate = outputDate;
		this.wattHourGenerated = wattHourGenerated;
		this.wattHourConsumed = wattHourConsumed;
	}
	 
}
